# Numpy Indexing and selection

In [1]:
#we can select elements or group of elements from a numpy array

In [4]:
import numpy as np

In [5]:
arr = np.arange(25)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arr[5]

5

In [8]:
arr[-3]

22

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [10]:
arr[:-5]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [14]:
#Slicing a 2d array

In [15]:
two_d_array=np.array([[10,20,30],[40,50,60],[70,80,90]])
two_d_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
two_d_array[0]

array([10, 20, 30])

In [17]:
two_d_array[0][1]

20

In [18]:
two_d_array[0,1]

20

Slice Notation

In [19]:
#to get a small matrices from a matrix

In [20]:
two_d_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
two_d_array[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
two_d_array[1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [23]:
two_d_array[:2, 1:]

array([[20, 30],
       [50, 60]])

In [24]:
arr = np.arange(1,11)

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
bool_arr = arr>5

In [27]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[arr<=5]

array([1, 2, 3, 4, 5])

In [30]:
arr_2d = np.arange(50).reshape(5, 10)

In [31]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
arr_2d[2:4,5:7]

array([[25, 26],
       [35, 36]])

In [33]:
arr_2d[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
arr_2d[-2:,-2:]

array([[38, 39],
       [48, 49]])

Iteration with arrays

In [37]:
itr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
itr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
for row in itr:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [40]:
for row in itr.flat:
    print(row)
    print('---------------------')

1
---------------------
2
---------------------
3
---------------------
4
---------------------
5
---------------------
6
---------------------
7
---------------------
8
---------------------
9
---------------------


In [41]:
a = np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [42]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [44]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [45]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [46]:
c=np.arange(6,12).reshape(2,3)

In [47]:
c

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
np.vstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [49]:
d = np.arange(30).reshape(2,15)

In [50]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
result = np.hsplit(d,3)

In [53]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [54]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [58]:
result_v = np.vsplit(d,2)

In [59]:
e = np.arange(12).reshape(3,4)

In [60]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
f = e>4

In [62]:
f

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
e[f]

array([ 5,  6,  7,  8,  9, 10, 11])

In [64]:
e[f]=-1

In [65]:
e

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [66]:
for row in e.flatten():
    print(row)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [68]:
for row in e.flat:
    print(row)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


In [69]:
for x in np.nditer(a,order='F'):
    print(x)


0
2
4
1
3
5
