# NumPy Arrays

In [1]:
import numpy as np

OnE dimensional Array

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

2-Dimensional Array

In [3]:
my_list_1=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Python's range with numpy

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#arange with stepsize
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
#zeros method in numpy for 1-d array
np.zeros(3)

array([0., 0., 0.])

In [10]:
#zeros with 2-d array
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#ones Method
np.ones(3)

array([1., 1., 1.])

In [12]:
#ones Method 2-d array
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Linspace Method

In [13]:
#this is same as arange method but atlast arange has the step size but linspace give sthe evenly spaced points between start and end
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Identity Matrix using Numpy(np.eye)

In [14]:
#it is useful when you are dealing with linear algebra problems
#Basically its a 2-d array with diagonally 1's present

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random Method

In [16]:
#this gives the alternate numbers from 0 to 1 
#helps in both 1-d and 2-d arrays

In [17]:
np.random.rand(3)

array([0.11784656, 0.62727433, 0.0091265 ])

In [18]:
#2d-array
np.random.rand(3,3)

array([[0.91267889, 0.51034336, 0.00279983],
       [0.65410558, 0.73287414, 0.19021931],
       [0.5755321 , 0.32501711, 0.83669944]])

Standard Normal distribution or Gaussian Distribution

In [19]:
#this will not return the numbers from 0 to 1 instead it returns standard normal distribution centre around Zero
np.random.randn(4)

array([ 1.7626904 , -0.41641417, -0.67655638,  0.68560475])

In [21]:
np.random.randn(4,4)

array([[ 1.48671358, -0.31164038, -2.49956516, -1.02993208],
       [ 0.55059812, -1.18386161,  0.77140214, -0.42665244],
       [ 0.62629005, -0.75479293,  0.65270345,  0.13761138],
       [ 0.15651308, -0.81717429, -1.47659589, -0.17426219]])

In [22]:
#randint gives the random values between the specified values
np.random.randint(1,100,10)

array([22, 39, 34,  2, 76, 45, 52, 40, 38, 81])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
#reshape method from 1-d to 2-d array
two_d_array=arr.reshape(5,5)

In [31]:
two_d_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
one_d_array = arr.reshape(25)

In [33]:
one_d_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
#to get the max and min values of array
one_d_array.max()

24

In [36]:

one_d_array.min()

0

In [37]:
#toget the indexes of max and min values in array
one_d_array.argmax()

24

In [38]:
one_d_array.argmin()

0