In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [8]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [12]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [13]:
a

array([[          1,           1,          16,         729],
       [      65536,     9765625, -2118184960,  -381759919],
       [          0, -1953380655,  1661992960, -1963437847]])

In [14]:
b = np.arange(3,15,4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
# it should be brodcastable
# any of the shape should be compatible

In [15]:
for x, y in np.nditer([a,b]):
    print(x,y)

1 3
1 3
16 3
729 3
65536 7
9765625 7
-2118184960 7
-381759919 7
0 11
-1953380655 11
1661992960 11
-1963437847 11
